export const questions = [
  { id: 1, text: "What carries oxygenated blood from the heart to the kidney?", answers: ["Arteries", "Veins", "Capillaries", "Nephrons"] },
  { id: 2, text: "What is the functional unit of the kidney?", answers: ["Nephron", "Alveoli", "Glomerulus", "Bowman’s capsule"] },
  { id: 3, text: "What is the percentage of water in urine?", answers: ["95%", "90%", "98%", "80%"] },
  { id: 4, text: "What is the pH range of human urine?", answers: ["4.5–5", "6–7", "5–6", "7–8"] },
  { id: 5, text: "What does OPEC stand for?", answers: ["Organization of Petroleum Exporting Countries", "Organization of Peace for Economic Countries", "Oil Producing Export Countries", "None of the above"] },
  { id: 6, text: "Where is the ICJ (International Court of Justice) headquartered?", answers: ["Hague, Netherlands", "Geneva", "Vienna", "Paris"] },
  { id: 7, text: "IUCN is headquartered in:", answers: ["Gland, Switzerland", "London", "New York", "Geneva"] },
  { id: 8, text: "Which country is not a member of OPEC?", answers: ["Austria", "Iran", "Iraq", "Saudi Arabia"] },
  { id: 9, text: "Who formed the All India Women’s Conference in 1927?", answers: ["Annie Besant and Margaret Cousins", "Sarojini Naidu", "Rani Lakshmi Bai", "Savitribai Phule"] },
  { id: 10, text: "Arya Mahila Samaj was founded by:", answers: ["Pandita Ramabai Sarasvati", "Sarla Devi", "Ramabai Rabade", "Margaret Cousins"] },
  { id: 11, text: "Bharat Stree Mahamandal was founded by:", answers: ["Sarla Devi Chaudharani", "Savitribai Phule", "Ramabai Rabade", "Pandita Ramabai"] },
  { id: 12, text: "Who founded the Ladies Social Conference?", answers: ["Ramabai Rabade", "Annie Besant", "Sarojini Naidu", "Pandita Ramabai"] },
  { id: 13, text: "When was the Election Commission of India established?", answers: ["25 Jan, 1950", "1947", "26 Jan, 1950", "15 Aug, 1949"] },
  { id: 14, text: "Under which article is the Election Commission mentioned?", answers: ["Article 324", "Article 320", "Article 350", "Article 311"] },
  { id: 15, text: "What change occurred in 1989 in the Election Commission?", answers: ["Became a multi-member body", "EC was dissolved", "Voting age increased", "Lok Sabha dissolved"] },
  { id: 16, text: "Who was the first Chief Election Commissioner?", answers: ["Sukumar Sen", "G.V. Mavlankar", "T.N. Seshan", "Rajiv Kumar"] },
  { id: 17, text: "Present Chief Election Commissioner (as per PDF)?", answers: ["Gyanesh Kumar Sandhu", "Sunil Arora", "Rajiv Kumar", "Om Prakash Rawat"] },
  { id: 18, text: "61st Constitutional Amendment reduced the voting age to:", answers: ["18", "16", "20", "19"] },
  { id: 19, text: "Which article deals with universal adult franchise?", answers: ["Article 326", "Article 325", "Article 327", "Article 324"] },
  { id: 20, text: "Pellagra is also known as:", answers: ["3D Disease", "2D Disease", "Protein Deficiency", "Metabolic Disease"] },
  { id: 21, text: "Which of the following is not a symptom of Pellagra?", answers: ["Diabetes", "Dementia", "Diarrhea", "Dermatitis"] },
  { id: 22, text: "Anaemia is caused due to the deficiency of:", answers: ["Iron", "Vitamin B1", "Calcium", "Vitamin D"] },
  { id: 23, text: "Neural Tube Defect occurs due to deficiency of:", answers: ["Folic Acid", "Vitamin A", "Vitamin D", "Iron"] },
  { id: 24, text: "The 10° channel divides:", answers: ["Andaman and Nicobar / Little Andaman and Car Nicobar", "India and Sri Lanka", "Lakshadweep and Maldives", "Minicoy and Maldives"] },
  { id: 25, text: "The 8° channel divides:", answers: ["Lakshadweep and Minicoy", "Andaman and Nicobar", "Sri Lanka and Maldives", "Little Andaman and Car Nicobar"] },
  { id: 26, text: "What type of forests receive more than 200 cm rainfall?", answers: ["Tropical evergreen forest", "Deciduous forest", "Thorn forest", "Montane forest"] },
  { id: 27, text: "Which forest covers the largest area in India?", answers: ["Deciduous (Monsoon forest)", "Mangrove", "Tropical Evergreen", "Coniferous"] },
  { id: 28, text: "Tendu leaves are found in which type of forest?", answers: ["Dry deciduous", "Mangrove", "Tropical evergreen", "Alpine"] },
  { id: 29, text: "Thorn forest trees have:", answers: ["Modified leaves", "Cones", "Spines", "Pneumatophores"] },
  { id: 30, text: "Which grass type is found in thorn forests?", answers: ["Tussocky grass", "Bamboo", "Shrub grass", "Alpine grass"] },
  { id: 31, text: "Which forest is found in the Himalayas' foothills?", answers: ["Montane", "Tropical", "Mangrove", "Thorn"] },
  { id: 32, text: "Bugyals are found at which height?", answers: ["3000–4000 m", "500–1000 m", "1000–2000 m", "Sea level"] },
  { id: 33, text: "Bugyals are also known as:", answers: ["Summer grasslands", "Tundra", "Alpine deserts", "Cold forests"] },
  { id: 34, text: "Shola forests are located in:", answers: ["Western Ghats", "Himalayas", "Eastern Ghats", "Central India"] },
  { id: 35, text: "Mangroves are also known as:", answers: ["Littoral/Swamp forest", "Montane forest", "Temperate forest", "Dry forest"] },
  { id: 36, text: "Pneumatophores are:", answers: ["Aerial roots in mangroves", "Epiphytes", "Modified stems", "Underground rhizomes"] },
  { id: 37, text: "Atomicity of phosgene is:", answers: ["4", "3", "2", "1"] },
  { id: 38, text: "Atomicity of sulphur is:", answers: ["8", "6", "2", "3"] },
  { id: 39, text: "Valency of inert gases is:", answers: ["0", "1", "2", "3"] },
  { id: 40, text: "Valency of halogens is:", answers: ["1", "2", "3", "0"] },
  { id: 41, text: "Valency of transition metals is:", answers: ["Variable", "1", "2", "4"] },
  { id: 42, text: "Ozone is found in:", answers: ["Stratosphere", "Troposphere", "Mesosphere", "Thermosphere"] },
  { id: 43, text: "Ozone is measured in:", answers: ["Dobson Unit", "Pascal", "mmHg", "mg/L"] },
  { id: 44, text: "Montreal Protocol is related to:", answers: ["Ozone protection", "Greenhouse gases", "Air pollution", "Soil erosion"] },
  { id: 45, text: "Mohiniyattam is a classical dance of:", answers: ["Kerala", "Tamil Nadu", "Karnataka", "Odisha"] },
  { id: 46, text: "Mohiniyattam is associated with which deity?", answers: ["Vishnu (as Mohini)", "Krishna", "Shiva", "Lakshmi"] },
  { id: 47, text: "Rajaji Formula was proposed in:", answers: ["1944", "1947", "1942", "1945"] },
  { id: 48, text: "Desai-Liaqat Pact happened in:", answers: ["1945", "1942", "1943", "1946"] },
  { id: 49, text: "Wavell Plan was introduced in:", answers: ["June 1945", "March 1945", "August 1946", "July 1947"] },
  { id: 50, text: "Relief rainfall occurs on:", answers: ["Windward side", "Leeward side", "Desert area", "Valley side"] },
  { id: 51, text: "Height increases, atmospheric pressure:", answers: ["Decreases", "Increases", "Remains same", "Fluctuates"] },
  { id: 52, text: "Layers in lake with sudden temperature drop:", answers: ["Thermocline", "Epilimnion", "Hypolimnion", "Pycnocline"] },
  { id: 53, text: "Major ocean relief features do NOT include:", answers: ["Seamount", "Continental shelf", "Deep sea plain", "Trench"] },
  { id: 54, text: "Seamounts are:", answers: ["Underwater mountains", "Coral islands", "Continental slopes", "Ocean ridges"] },
  { id: 55, text: "The first university for Indian women was established in:", answers: ["1916", "1905", "1921", "1947"] },
  { id: 56, text: "Who established the first Indian women’s university?", answers: ["D.K. Karve", "Annie Besant", "Savitribai Phule", "Sarojini Naidu"] },
  { id: 57, text: "Ionic bond involves:", answers: ["Transfer of electrons", "Sharing of electrons", "Covalent link", "Van der Waals forces"] },
  { id: 58, text: "Covalent bond involves:", answers: ["Sharing of electrons", "Transfer of protons", "Ion exchange", "Electron removal"] },
  { id: 59, text: "Formula for Alkane:", answers: ["CnH2n+2", "CnH2n", "CH4", "CnHn"] },
  { id: 60, text: "Alkanes have:", answers: ["High boiling point", "Weak bonds", "Low boiling point", "Acidic nature"] },
  { id: 61, text: "Butane has how many carbon atoms?", answers: ["4", "2", "3", "6"] },
  { id: 62, text: "Hexane has how many carbon atoms?", answers: ["6", "4", "5", "7"] },
  { id: 63, text: "Nokrek and Balphakram are located in:", answers: ["Meghalaya", "Arunachal Pradesh", "Mizoram", "Assam"] },
  { id: 64, text: "Ministry that conducts surveys every 5 years:", answers: ["MoSPI", "MoHUA", "MoEFCC", "MoE"] },
  { id: 65, text: "Losoong and Namsoong festivals belong to:", answers: ["Sikkim", "Arunachal Pradesh", "Nagaland", "Manipur"] },
  { id: 66, text: "Purvanchal hills are in:", answers: ["Eastern India", "Rajasthan", "Western Ghats", "Punjab"] },
  { id: 67, text: "Rajasthan is known for:", answers: ["Deserts", "Forests", "Wetlands", "Volcanoes"] },
  { id: 68, text: "Manikaran is a place in:", answers: ["Himachal Pradesh", "Uttarakhand", "Jammu & Kashmir", "Sikkim"] },
  { id: 69, text: "Ladakh lies in:", answers: ["Union Territory of Ladakh", "Himachal", "Jammu", "Kashmir"] },
  { id: 70, text: "Name the constitutional part related to Panchayati Raj:", answers: ["Part IX", "Part VI", "Part IV", "Part XI"] },
  { id: 71, text: "Articles for Municipalities:", answers: ["243P–243ZG", "243–243O", "243A–243G", "240–249"] },
  { id: 72, text: "Which forest contains epiphytes?", answers: ["Tropical Evergreen", "Desert", "Alpine", "Deciduous"] },
  { id: 73, text: "Which forest has cone-shaped trees?", answers: ["Coniferous", "Mangrove", "Montane", "Thorn"] },
  { id: 74, text: "What tribe resides in Bugyals?", answers: ["Bhutia", "Nishi", "Garo", "Khasi"] },
  { id: 75, text: "Alkali metals have valency:", answers: ["1", "0", "2", "3"] },
  { id: 76, text: "Chalcogens have valency:", answers: ["2", "1", "3", "0"] },
  { id: 77, text: "Nictogen group elements have valency:", answers: ["3", "2", "1", "0"] },
  { id: 78, text: "Vivipary in plants is seen in:", answers: ["Mangroves", "Montane plants", "Alpine grasses", "Epiphytes"] },
  { id: 79, text: "Atmospheric pressure is measured in:", answers: ["Pascal", "Celsius", "Dobson", "Lux"] },
  { id: 80, text: "Ocean currents are:", answers: ["Done in detail previously", "Done briefly", "Not discussed", "Ignored"] }
];
